### PR TITLE
Establish index.staging.scheme.org

### PR DESCRIPTION
**Pull request by lassik**
cc @arvyy

### CODE REVIEW

**Comment by lassik** [comment]
Context: https://srfi-email.schemers.org/schemeorg/msg/25650770/

**Comment by arthurgleckler** [comment]
I haven't been able to push this to Gandi because their login system is down.  I will do that as soon as it's working.

**Comment by arthurgleckler** [comment]
Is anyone else able to log into Gandi.net?  I've filed a ticket after having it fail for several hours across Android, Linux, and MacOS, but I'm wondering whether anyone else is seeing this.  The page doesn't load properly, and the Javascript console shows 404s and errors claiming that I'm running an ad blocker, which I'm not.

**Comment by arthurgleckler** [comment]
I'm not sure what to do.  I can't get Gandi tech support to respond.  I've filed two tickets, but I can't check their status because I have to log in to do so, and logging in is the whole problem.

**Comment by arthurgleckler** [comment]
I finally managed to log in and push this change.  Gandi's login page is still broken for me, but I managed to work around that.

**Comment by lassik** [comment]
@arthurgleckler Thank you. Sorry you had to go through the trouble with Gandi. I don't know what's up with them.

Thanks to @arvyy's work, https://index.staging.scheme.org/ is now live.

**Pull request merged**
