### PR TITLE
add racket scheme implementations

### PR DESCRIPTION
**Pull request by spdegabrielle**

### CODE REVIEW

**Comment by spdegabrielle** [comment]
Does this also need a change to `/dns/scheme.org.zone` ?

Perhaps: 
```
gambit IN CNAME gambitscheme.org.
```
inserted at line 86? 
 https://github.com/schemeorg/schemeorg/blob/370fc2625030807baf0a33ce1112c9cbf67bd583/dns/scheme.org.zone#L86

**Comment by arthurgleckler** [comment]
Wait, I merged this, but have you asked the Racket folks whether they want this CNAME? We always check with the implementers first.

**Comment by spdegabrielle** [comment]
sorry I was assuming it was a redirect to racket-lang.org like the https://bigloo.scheme.org/ link on https://www.scheme.org redirects to https://www-sop.inria.fr/indes/fp/Bigloo/

I don't think there would be a problem with a redirect on the scheme.org website but agree it would be appropriate to log an issue at https://github.com/racket/racket/issues/new in the same way you [asked the Chez Scheme maintainers](https://github.com/cisco/ChezScheme/issues/644).

QQ: if you can't get permission to create racket.scheme.org would that mean Racket could not be included in the implementations listed on the https://www.scheme.org home page? If this is a **condition of inclusion** it should be included when asking the maintainers.

**Comment by arthurgleckler** [comment]
> sorry I was assuming it was a redirect to racket-lang.org like the https://bigloo.scheme.org/ link on https://www.scheme.org redirects to https://www-sop.inria.fr/indes/fp/Bigloo/

Yes, that's right, but we're careful not to establish such redirects until we have permission from the maintainers of the specific Scheme.

> I don't think there would be a problem with a redirect on the scheme.org website but agree it would be appropriate to log an issue at https://github.com/racket/racket/issues/new in the same way you [asked the Chez Scheme maintainers](https://github.com/cisco/ChezScheme/issues/644).

Good idea.  I've filed a request for an answer at [](https://github.com/racket/racket/issues/4794).

> QQ: if you can't get permission to create racket.scheme.org would that mean Racket could not be included in the implementations listed on the https://www.scheme.org home page? If this is a **condition of inclusion** it should be included when asking the maintainers.

No, it can definitely still be included.

**Pull request merged**
